name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*.*.*.*'  # Trigger only on version tags like v1.2.3.4
  workflow_dispatch:
    inputs:
      target_tag:
        description: "Publish particular tag"
        type: string
        required: false
        default: "master"
      dry-run:
        description: "Publish to a dry-run package"
        type: boolean
        required: true
        default: true
      skip-duplicate:
        description: "Skip publishing if the package already exists"
        type: boolean
        default: false

env:
  SKIP_DUPLICATE: ${{ inputs.skip-duplicate }}
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
  SNK_FILE: ${{ secrets.SNK_KEY }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        ref: ${{ inputs.target_tag || github.ref }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '9.0.x'
        
    - name: Publish to NuGet (Dry Run)
      if: ${{ inputs.dry-run == true }}
      run: make publish-nuget-dry-run

    - name: Publish to NuGet (Production)
      if: ${{ inputs.dry-run == false }}
      run: make publish-nuget
